# Generated by Django 5.0.7 on 2026-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_admissionapplication_student_user_teacher_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
